---
ID: "374592f2-0908-4f5a-9896-b1a1390e5501"
Parent: "2e5760a6-6df8-43f1-a5ef-2edf66f94185"
Template: "2b2ef8a6-34b2-4fe9-bfdb-ef55b8766be6"
Path: /sitecore/content/cdpsitecore/Home/CDPEvents/Product2
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product 2
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221221T084512Z
    - ID: "79f92ce1-4d1d-4ceb-9826-7bb36c466d7f"
      Hint: ProductDescription
      Value: "<span>Fast food is a type of mass-produced food designed for commercial resale, with a strong priority placed on speed of service. It is a commercial term, limited to food sold in a restaurant or store with frozen, preheated or precooked ingredients and served in packaging for take-out/take-away. Fast food was created as a commercial strategy to accommodate large numbers of busy commuters, travelers and wage workers. In 2018, the fast food industry was worth an estimated $570 billion globally.</span>"
    - ID: "82eed051-14d0-48ab-9d8c-369ee2beba6e"
      Hint: ProductTitle
      Value: Fast Food
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac025856-090b-4b9e-bfb1-cae6290336c6"
    - ID: "9f480d27-4555-4374-85ac-c721abc95e44"
      Hint: ProductImage
      Value: |
        <image mediaid="{71B6F24E-40E5-4531-8582-EE36FA3761D2}" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221221T085823Z
